### ISSUE TITLE
is there possiable to support local dxf file?

### ISSUE THREAD

**Issue by belimked** [VovaStelmashchuk/nest2d#6]
there are some reasons that visit S3 is not friendly from local env.  as East-Asian area, so could you set switch which could be still support local dxf file? i found local file function in v0.5.2 

thank a lot
respect

**Comment by VovaStelmashchuk** [comment]
No, there is no reason for that. Adding S3 was a mistake (a bad technical decision).

Now I'm working on the next version, which will save DXF as SVG in MongoDB as text field. The new version will use less Java; I plan to move as much as possible to the Nuxt backend.

**Comment by belimked** [comment]
nice to hear it.
cheers

**Comment by VovaStelmashchuk** [comment]
FYI, project rewrite to save dxf and svg file to mongo db and no s3 require.
